const D=window.PLANNER_DATA, $=id=>document.getElementById(id);
const months=['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];
const types=D.visitTypes, stores=D.stores; let events=[], deferredPrompt=null;
const date=s=>{const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)};
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const addDays=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};
const mins=t=>{const [h,m]=t.split(':').map(Number);return h*60+m};
const hm=m=>`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;
const typeColor=t=>(types.find(x=>x.id===t)||{}).color||'#64748b';
const monthIndex=()=>months.indexOf($('monthSel').value);
function dist(a,b){const R=6371,rad=x=>x*Math.PI/180,dLat=rad(b.lat-a.lat),dLng=rad(b.lng-a.lng),v=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLng/2)**2;return 2*R*Math.asin(Math.sqrt(v));}
function travel(a,b){return Math.max(15,Math.round(dist(a,b)*2.1+25));}
function nearestRoute(list){let cur=D.home,left=[...list],out=[];while(left.length){left.sort((a,b)=>dist(cur,a)-dist(cur,b));const n=left.shift();out.push(n);cur=n}return out}
function periodFor(d){return D.periods.find(p=>d>=date(p.planStart)&&d<=date(p.planEnd))||D.periods.find(p=>d>=date(p.campStart)&&d<=date(p.campEnd))||D.periods.at(-1)}
function weekStart(d){return iso(addDays(d,-((d.getDay()+6)%7)))}
function workStart(d){return d.getDay()===0?'13:00':'08:00'}
function weeksOfMonth(y,m){const first=new Date(y,m,1),last=new Date(y,m+1,0),out=[];let cur=addDays(first,-((first.getDay()+6)%7));while(cur<=last){out.push({label:`${iso(cur).slice(5)} al ${iso(addDays(cur,6)).slice(5)}`,start:iso(cur),end:iso(addDays(cur,6))});cur=addDays(cur,7)}return out}
function push(ev){events.push({id:crypto.randomUUID(),...ev})}
function focusText(type,s,p){
 const method='1 foco · 1 práctica · 1 dueño · 1 fecha.';
 if(type==='VPP/SOA')return `${p.name}: definir resultado, hábito y responsable. Pregunta: ¿qué indicador moverás y con qué comportamiento? ${method}`;
 if(type==='Observe & Coach')return `Experiencia, conexión, bebida u orden: observar, nombrar, practicar y repetir. Pregunta: ¿qué harás distinto en la próxima hora? ${method}`;
 if(type==='WOE / Inventario')return `WOE e inventario: disponibilidad, variación, causa raíz y evidencia. Pregunta: ¿dónde se pierde producto, tiempo o disponibilidad? ${method}`;
 if(type==='Conexión + Seguimiento')return `Validar compromiso y remover barrera. Pregunta: ¿qué cambió desde la última visita y qué necesitas para sostenerlo? ${method}`;
 return 'Administración del rol DM: decisión clara, dueño y fecha.';
}
function addTravel(day,from,to,start){const duration=travel(from,to);push({date:iso(day),start:hm(start),end:hm(start+duration),type:'Traslado',title:`🚗 Traslado · ${from.name||'Casa'} → ${to.short||to.name}`,store:to.cc||'',storeName:to.name,focus:`${duration} min estimados con colchón`,maps:to.maps||'',routeOnly:true});return start+duration}
function scheduleDay(day,visits){let t=mins(workStart(day)),cur=D.home;const route=nearestRoute(visits.map(v=>v.store));route.forEach((s,i)=>{t=addTravel(day,cur,s,t);const v=visits.find(x=>x.store.cc===s.cc),duration=(types.find(x=>x.id===v.type)||{}).minutes||90;push({date:iso(day),start:hm(t),end:hm(t+duration),type:v.type,title:`${v.type} · ${s.cc} ${s.name}`,store:s.cc,storeName:s.name,manager:s.manager,focus:focusText(v.type,s,periodFor(day)),maps:s.maps});t+=duration;if(i===0&&route.length>1){push({date:iso(day),start:hm(t),end:hm(t+60),type:'Comida',title:'🍽️ Comida',focus:'Pausa planificada para sostener la jornada.'});t+=60}cur=s});if(route.length)addTravel(day,cur,D.home,t)}
function admin(day,start,end,title,focus){push({date:iso(day),start,end,type:'Administrativo',title,focus})}
function generateBase(){
 events=[];const start=date(D.start),end=date(D.end);
 for(let d=new Date(start);d<=end;d=addDays(d,1)){
   const dow=d.getDay();
   if(dow===1){admin(d,'08:00','09:00','Lunes · revisar WOE PM','Revisar evidencia del SM, variaciones, disponibilidad y barreras.');admin(d,'09:15','10:30','Lunes · cruce Perfil Tienda + CeNtro Partner','Leer dato, retro y prioridad antes de decidir.');admin(d,'10:45','12:00','Lunes · priorizar visitas y soporte','Elegir un foco por tienda, agenda y escalaciones.');admin(d,'12:15','13:00','Lunes · soporte','Sistema, Mantenimiento, COA o Capacitación: responsable y ETA.');}
   if(dow===2){admin(d,'08:00','10:00','Martes · Junta Regional DM','Recibir prioridades, riesgos y cambios operativos.');admin(d,'10:15','11:00','Martes · bajada al equipo','1 dato, 1 prioridad, 1 conducta y 1 fecha por tienda.');admin(d,'11:15','12:00','Martes · compromisos','Actualizar acciones, barreras y validación.');}
   if(dow===0)push({date:iso(d),start:'17:00',end:'18:00',type:'WOE / Inventario',title:'Domingo PM · WOE e inventario SM',focus:'SM: conteo, variación, evidencia y acción. DM: revisa el lunes.',protected:true});
 }
 D.periods.forEach(p=>{
   const days=[];for(let d=date(p.planStart);d<=date(p.planEnd);d=addDays(d,1))if(d>=start&&d<=end&&[0,3,4,5,6].includes(d.getDay()))days.push(new Date(d));
   const requested=['VPP/SOA','Observe & Coach','WOE / Inventario','Conexión + Seguimiento'];let idx=0;
   requested.forEach(type=>{const clusters=[['38515','38456','43193'],['38604','38401','38368'],['38333','38339','38862'],['38894']];clusters.forEach(cluster=>{const batch=cluster.map(cc=>stores.find(s=>s.cc===cc)).filter(Boolean);const day=days[idx%days.length];scheduleDay(day,batch.map(store=>({type,store})));idx+=2})});
 });
 // Garantía de contacto semanal: solo miércoles a domingo y respetando traslado.
 for(let w=new Date(start);w<=end;w=addDays(w,7)){
   const week=weekStart(w),existing=new Set(events.filter(e=>e.store&&weekStart(date(e.date))===week&&!['Traslado','Comida'].includes(e.type)).map(e=>e.store));
   const missing=stores.filter(s=>!existing.has(s.cc)),days=[2,3,4,5,6].map(n=>addDays(w,n)).filter(d=>d<=end);
   [['38333','38339','38862'],['38604','43193','38401'],['38515','38456'],['38368','38894']].forEach((cluster,i)=>{const batch=missing.filter(s=>cluster.includes(s.cc));if(batch.length)scheduleDay(days[i%days.length],batch.map((store,j)=>({type:j?'Conexión + Seguimiento':'Observe & Coach',store})))})
 }
 save();
}
function save(){localStorage.setItem('plannerEventsV20',JSON.stringify(events))}
function load(){events=JSON.parse(localStorage.getItem('plannerEventsV20')||'[]');if(!events.length)generateBase()}
function selectedEvents(){const m=monthIndex(),type=$('typeSel').value,store=$('storeSel').value.split(' ')[0],q=$('searchInput').value.toLowerCase();let out=events.filter(e=>date(e.date).getMonth()===m&&date(e.date).getFullYear()===2026);if($('weekSel').value!=='Todas'){const[a,b]=$('weekSel').value.split('|').map(date);out=out.filter(e=>date(e.date)>=a&&date(e.date)<=b)}if(type!=='Todas')out=out.filter(e=>e.type===type);if(store!=='Todas')out=out.filter(e=>e.store===store);if(q)out=out.filter(e=>JSON.stringify(e).toLowerCase().includes(q));return out.sort((a,b)=>(a.date+a.start).localeCompare(b.date+b.start))}
function renderKpis(){const ev=selectedEvents(),physical=ev.filter(e=>e.store&&!['Traslado','Comida','Administrativo'].includes(e.type)),covered=new Set(physical.map(e=>e.store)),high=physical.filter(e=>stores.find(s=>s.cc===e.store)?.priority==='alta').length;const k=[['VISITAS MES',physical.length,'operación y capacidad'],['TIENDAS CUBIERTAS',`${covered.size}/10`,'portafolio'],['PRIORIDAD ALTA',high,'foco crítico'],['O&C',physical.filter(e=>e.type==='Observe & Coach').length,'práctica en turno'],['WOE',physical.filter(e=>e.type==='WOE / Inventario').length,'control y evidencia'],['SOPORTE',ev.filter(e=>e.type==='Soporte').length,'barreras removidas']];$('kpis').innerHTML=k.map(x=>`<div class="panel kpi"><small>${x[0]}</small><b>${x[1]}</b><span>${x[2]}</span></div>`).join('')}
function renderIntention(){const p=periodFor(new Date(2026,monthIndex(),15));$('intention').innerHTML=`<h2>Intencionalidad</h2><div class="intCard"><h3>${p.name}</h3><p><b>Plan:</b> ${p.planStart} a ${p.planEnd}</p><p><b>Campaña:</b> ${p.campStart} a ${p.campEnd}</p><p><b>Regla:</b> 1 foco · 1 práctica · 1 dueño · 1 fecha.</p></div><div class="intCard"><h3>Guía DM</h3><p><b>Antes:</b> dato + WOE + retro.</p><p><b>Durante:</b> observa → pregunta → practica.</p><p><b>Después:</b> evidencia en 72 h.</p><span class="pill alta">Alta: Luna, Patio, Cosmo N1</span></div>`}
function renderCalendar(){const m=monthIndex(),first=new Date(2026,m,1),start=addDays(first,-((first.getDay()+6)%7));$('calTitle').textContent=`Agenda · ${months[m]} 2026`;$('legend').innerHTML=types.map(t=>`<span style="--c:${t.color}">${t.label}</span>`).join('');let html=['L','M','X','J','V','S','D'].map(d=>`<div class="dow">${d}</div>`).join('');for(let i=0;i<42;i++){const d=addDays(start,i),ev=selectedEvents().filter(e=>e.date===iso(d));html+=`<div class="day ${d.getMonth()!==m?'muted':''}"><div class="num">${d.getDate()}</div>${ev.slice(0,7).map(e=>`<div class="event ${e.protected?'protected':''}" style="--c:${typeColor(e.type)}" title="${e.title}">${e.start} ${e.title}</div>`).join('')}${ev.length>7?`<div class="more">+${ev.length-7} más</div>`:''}</div>`}$('calendar').innerHTML=html}
function renderRouteOptions(){const ev=selectedEvents().filter(e=>e.store&&!e.routeOnly&&!['Comida','Administrativo'].includes(e.type)),dates=[...new Set(ev.map(e=>e.date))].sort();$('routeDateSel').innerHTML=dates.map(d=>`<option value="${d}">${d.slice(8)} ${months[Number(d.slice(5,7))-1].slice(0,3)}</option>`).join('');$('routeDateSel').onchange=renderRoute;renderRoute();renderCoverage()}
function renderRoute(){const day=$('routeDateSel').value,items=selectedEvents().filter(e=>e.date===day&&e.store&&!e.routeOnly&&!['Comida','Administrativo'].includes(e.type)),route=nearestRoute(items.map(e=>stores.find(s=>s.cc===e.store)).filter(Boolean));let cur=D.home;$('routeList').innerHTML=route.map((s,i)=>{const m=travel(cur,s),line=`<div class="routeStep"><b>${i?'Parada '+i:'Salida'}</b><br>${cur.name} → ${s.name} · ${m} min<br><a href="${s.maps}" target="_blank">Abrir Maps</a></div>`;cur=s;return line}).join('')+(route.length?`<div class="routeStep"><b>Regreso</b><br>${route.at(-1).name} → Casa Enrique · ${travel(route.at(-1),D.home)} min</div>`:'<p>Sin ruta para el filtro actual.</p>');drawRoute(route)}
function drawRoute(route){const box=$('routeMap');box.innerHTML='';const pts=[...route,D.home];if(!pts.length)return;const lats=pts.map(p=>p.lat),lngs=pts.map(p=>p.lng),pos=p=>({x:20+(p.lng-Math.min(...lngs))/(Math.max(...lngs)-Math.min(...lngs)||1)*250,y:20+(Math.max(...lats)-p.lat)/(Math.max(...lats)-Math.min(...lats)||1)*150});let prev=D.home;route.concat([D.home]).forEach(p=>{const a=pos(prev),b=pos(p),edge=document.createElement('div');edge.className='edge';edge.style.cssText=`left:${a.x}px;top:${a.y}px;width:${Math.hypot(b.x-a.x,b.y-a.y)}px;transform:rotate(${Math.atan2(b.y-a.y,b.x-a.x)*180/Math.PI}deg)`;box.appendChild(edge);prev=p});pts.forEach(p=>{const o=pos(p),node=document.createElement('div');node.className='node '+(p.name==='Casa Enrique'?'home':'');node.style.left=o.x+'px';node.style.top=o.y+'px';node.innerHTML=`<span>${p.short||'Casa'}</span>`;box.appendChild(node)})}
function renderCoverage(){const m=monthIndex();$('coverageList').innerHTML=weeksOfMonth(2026,m).map(w=>{const set=new Set(events.filter(e=>date(e.date)>=date(w.start)&&date(e.date)<=date(w.end)&&e.store&&!['Traslado','Comida'].includes(e.type)).map(e=>e.store));return `<div class="coverageItem"><b>${w.label}</b><br>${set.size}/10 tiendas · ${set.size===10?'✅ contacto':'⚠️ revisar'}</div>`}).join('')}
function renderDetails(){let ev=selectedEvents(),q=$('detailSearch').value?.toLowerCase();if(q)ev=ev.filter(e=>JSON.stringify(e).toLowerCase().includes(q));$('detailTable').innerHTML='<tr><th>Fecha</th><th>Hora</th><th>Actividad</th><th>Tienda / SM</th><th>Salida</th><th>Ruta</th></tr>'+ev.map(e=>`<tr><td>${e.date}</td><td>${e.start}-${e.end}</td><td><b>${e.title}</b><br>${e.type}</td><td>${e.storeName||'-'}<br><small>${e.manager||''}</small></td><td>${e.focus||''}</td><td>${e.maps?`<a href="${e.maps}" target="_blank">Maps</a>`:'-'}</td></tr>`).join('')}
function render(){const m=monthIndex(),prev=$('weekSel').value||'Todas';$('weekSel').innerHTML='';$('weekSel').add(new Option('Todas','Todas'));weeksOfMonth(2026,m).forEach(w=>$('weekSel').add(new Option(w.label,`${w.start}|${w.end}`)));if([...$('weekSel').options].some(o=>o.value===prev))$('weekSel').value=prev;renderKpis();renderIntention();renderCalendar();renderRouteOptions();renderDetails()}
function addBlock(){const a=$('blockFrom').value,b=$('blockTo').value,reason=$('blockReason').value||'Bloqueo';if(!a||!b)return alert('Selecciona fechas de bloqueo.');events=events.filter(e=>e.date<a||e.date>b||e.type==='Administrativo');for(let d=date(a);d<=date(b);d=addDays(d,1))push({date:iso(d),start:'00:00',end:'23:59',type:'Bloqueo',title:`⛔ ${reason}`,focus:'Bloqueo todo el día; reprograma visita y validación.'});save();render()}
function downloadICS(ev,name){const fmt=(d,t)=>d.replaceAll('-','')+'T'+t.replace(':','')+'00',body=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Planner DM 2.0//ES'].concat(ev.map(e=>['BEGIN:VEVENT',`UID:${e.id}@planner-dm`,`DTSTAMP:${fmt(iso(new Date()),'00:00')}Z`,`DTSTART:${fmt(e.date,e.start)}`,`DTEND:${fmt(e.date,e.end)}`,`SUMMARY:${e.title}`,`LOCATION:${e.storeName||''}`,`DESCRIPTION:${(e.focus||'').replace(/\n/g,' ')}`,'END:VEVENT'].join('\n'))).concat(['END:VCALENDAR']).join('\n');const blob=new Blob([body],{type:'text/calendar'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click()}
function init(){months.forEach(m=>$('monthSel').add(new Option(m,m)));$('monthSel').value='Agosto';['Todas',...types.map(t=>t.id)].forEach(t=>$('typeSel').add(new Option(t,t)));['Todas',...stores.map(s=>`${s.cc} · ${s.name}`)].forEach(t=>$('storeSel').add(new Option(t,t)));['monthSel','weekSel','typeSel','storeSel','searchInput','detailSearch'].forEach(id=>$(id).addEventListener('input',render));$('generateBtn').onclick=()=>{generateBase();render()};$('resetBtn').onclick=()=>{localStorage.removeItem('plannerEventsV20');generateBase();render()};$('blockBtn').onclick=addBlock;$('icsMonthBtn').onclick=()=>downloadICS(selectedEvents(),`Planner_DM_${$('monthSel').value}_2026.ics`);$('icsYearBtn').onclick=()=>downloadICS(events,'Planner_DM_2026.ics');$('copyRouteBtn').onclick=()=>{navigator.clipboard.writeText([...document.querySelectorAll('.routeStep')].map(x=>x.innerText).join('\n'));alert('Ruta copiada')};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hidden')});$('installBtn').onclick=()=>deferredPrompt?.prompt();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');load();render()}
init();
