const D=window.PLANNER_DATA; const $=id=>document.getElementById(id);
const months=['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];
const types=D.visitTypes, stores=D.stores; let events=[]; let deferredPrompt=null;
function date(s){const [y,m,d]=s.split('-').map(Number); return new Date(y,m-1,d)}
function iso(dt){return dt.toISOString().slice(0,10)}
function addDays(d,n){const x=new Date(d); x.setDate(x.getDate()+n); return x}
function mins(t){const [h,m]=t.split(':').map(Number);return h*60+m} function hm(m){return String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0')}
function monthIndex(){return months.indexOf($('monthSel').value)} function typeColor(t){return (types.find(x=>x.id==t)||{}).color||'#777'}
function dist(a,b){const R=6371,rad=x=>x*Math.PI/180; const dLat=rad(b.lat-a.lat),dLng=rad(b.lng-a.lng); const v=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLng/2)**2; return 2*R*Math.asin(Math.sqrt(v));}
function travel(a,b){return Math.max(12,Math.round(dist(a,b)*2.1+18)+10)} // +10 min realismo
function nearestRoute(list){let cur=D.home, left=[...list], out=[]; while(left.length){left.sort((a,b)=>dist(cur,a)-dist(cur,b)); const n=left.shift(); out.push(n); cur=n;} return out;}
function periodFor(d){return D.periods.find(p=>d>=date(p.planStart)&&d<=date(p.planEnd))||D.periods.find(p=>d>=date(p.campStart)&&d<=date(p.campEnd))||D.periods[D.periods.length-1]}
function workStart(d){const dow=d.getDay(); if(dow==1||dow==3||dow==4) return '08:30'; if(dow==2||dow==5) return '09:00'; return '13:00'}
function sameWeek(d){const x=new Date(d); const day=(x.getDay()+6)%7; const m=addDays(x,-day); return iso(m)}
function getWeeksOfMonth(y,m){let first=new Date(y,m,1), last=new Date(y,m+1,0), weeks=[]; let cur=addDays(first,-((first.getDay()+6)%7)); while(cur<=last){weeks.push({label:`${iso(cur).slice(5)} al ${iso(addDays(cur,6)).slice(5)}`,start:iso(cur),end:iso(addDays(cur,6))});cur=addDays(cur,7)} return weeks}
function push(ev){events.push({id:crypto.randomUUID(),...ev})}
function visitTitle(type,s){ if(type==='CDD') return `CDD_${s.manager.split(' ')[0]} ${s.manager.split(' ').at(-1)}`; return `${type} · ${s.cc} ${s.name}` }
function focusText(type,s,p){const map={APRENDIZAJE:'enseñar aptitudes, claridad de estándares y seguimiento hombro a hombro',APROPIACION:'coaching sobre comportamientos, autonomía y resolución de problemas',ASESORAMIENTO:'alentar crecimiento y utilizar al gerente como referente para otros'}; let base=map[s.approach]||'seguimiento'; if(type==='VPP/SOA') return `Preparación de campaña ${p.name}: brechas, SOA, planes, prioridades y compromisos. Approach ${s.approach}: ${base}.`;
 if(type==='System Check Inventario') return `Inventario y procesos: disponibilidad, Daily Record Book, mermas, controles y precisión. Approach ${s.approach}: ${base}.`;
 if(type==='Observe & Coach') return `Observación en piso: distribución, canales, ejecución, coaching inmediato y cierre de aprendizajes. Approach ${s.approach}: ${base}.`;
 if(type==='Conexión rápida') return `Contacto específico para acelerar resultados: conexión, reconocimiento, seguimiento de compromisos y siguiente paso.`;
 if(type==='CDD') return `Conversación de desempeño y desarrollo: aspiraciones, fortalezas, feedback claro, plan de crecimiento y compromisos.`;
 return 'Actividad administrativa del rol DM.'}
function addTravel(day,from,to,start){const m=travel(from,to); push({date:iso(day),start:hm(start),end:hm(start+m),type:'Traslado',title:`🚗 Traslado · ${from.name||'Casa'} → ${to.short||to.name}`,store:to.cc||'',storeName:to.name,focus:`${m} min aprox con 10 min de colchón`,maps:to.maps||'',routeOnly:true}); return start+m;}
function scheduleDay(day,visits){let t=mins(workStart(day)); let cur=D.home; const route=nearestRoute(visits.map(v=>v.store)); route.forEach((s,i)=>{t=addTravel(day,cur,s,t); const v=visits.find(x=>x.store.cc===s.cc); const dur=types.find(x=>x.id===v.type).minutes; push({date:iso(day),start:hm(t),end:hm(t+dur),type:v.type,title:visitTitle(v.type,s),store:s.cc,storeName:s.name,manager:s.manager,focus:focusText(v.type,s,periodFor(day)),maps:s.maps}); t+=dur; if(i===0){push({date:iso(day),start:hm(t),end:hm(t+60),type:'Comida',title:`🍽️ Comida · ${s.short}`,store:s.cc,storeName:s.name,focus:'Media jornada para sostener energía y agenda de 10 hrs.'}); t+=60;}}); t=addTravel(day,cur=route.at(-1)||D.home,D.home,t);}
function generateBase(){events=[]; const start=date(D.start), end=date(D.end); // protegidos martes
 for(let d=new Date(start);d<=end;d=addDays(d,1)){ if(d.getDay()==2) push({date:iso(d),start:'12:30',end:'14:00',type:'Adaptación a lo inesperado',title:'Martes 12:30–14:00 libre · Junta Regional protegida',focus:'No agendar visitas en este espacio. Si hay junta, usar este bloque.',protected:true}); }
 // campañas arranque 6am
 [{d:'2026-07-20',p:'Summer'},{d:'2026-08-31',p:'Fall'},{d:'2026-11-03',p:'Xmas'}].forEach(x=>{const s=stores.find(z=>z.priority==='alta'); push({date:x.d,start:'06:00',end:'08:00',type:'Arranque campaña',title:`🚀 Arranque campaña ${x.p} · ${s.name}`,store:s.cc,storeName:s.name,manager:s.manager,focus:'Primer día de campaña: validación visual, abasto, comunicación y experiencia.',maps:s.maps})});
 // CDD julio y octubre una por gerente
 [6,9].forEach(m=>{let ds=[]; for(let d=new Date(2026,m,1);d<=new Date(2026,m+1,0);d=addDays(d,1)){ if([1,3,4,5].includes(d.getDay())) ds.push(new Date(d)); } stores.forEach((s,i)=>scheduleDay(ds[i]||ds[0],[{type:'CDD',store:s}])); });
 // visitas por periodo: 4 tipos por tienda por periodo, evitando repetición misma semana
 D.periods.forEach(p=>{const days=[]; for(let d=date(p.planStart);d<=date(p.planEnd);d=addDays(d,1)){ if(d>=start && [1,2,3,4,5].includes(d.getDay())) days.push(new Date(d)); }
 const req=['VPP/SOA','System Check Inventario','Observe & Coach','Conexión rápida']; let idx=0; req.forEach((typ,ti)=>{const byCluster=[['38515','38456','43193'],['38604','38401','38368'],['38333','38339','38862'],['38894']]; byCluster.forEach(cluster=>{const batch=cluster.map(cc=>stores.find(s=>s.cc==cc)).filter(Boolean); const d=days[idx%days.length]; scheduleDay(d,batch.map(s=>({type:typ,store:s}))); idx+=2;}); }); });
 // cobertura semanal: una visita max por tienda por semana para semanas que falten
 const allWeeks=[]; for(let w=date(D.start);w<=date(D.end);w=addDays(w,7)) allWeeks.push(new Date(w));
 allWeeks.forEach((w,wi)=>{const existing=new Set(events.filter(e=>e.store&&sameWeek(date(e.date))===iso(w)&&!['Traslado','Comida'].includes(e.type)).map(e=>e.store)); const missing=stores.filter(s=>!existing.has(s.cc)); const days=[0,1,2,3,4].map(n=>addDays(w,n)).filter(d=>d<=end); const clusters=[['38333','38339','38862'],['38604','43193','38401'],['38515','38456'],['38368','38894']]; clusters.forEach((cl,ci)=>{const batch=missing.filter(s=>cl.includes(s.cc)).slice(0,3); if(batch.length){const d=days[(ci+wi)%days.length]; scheduleDay(d,batch.map((s,j)=>({type:j==0?'Observe & Coach':'Conexión rápida',store:s})));}})});
 // fines de semana: al menos 2 días sábado/domingo por mes, jornada completa acompañamiento
 for(let m=6;m<12;m++){let wends=[]; for(let d=new Date(2026,m,1);d<=new Date(2026,m+1,0);d=addDays(d,1)){ if(d.getDay()==0||d.getDay()==6) wends.push(new Date(d)); } wends.slice(0,2).forEach((d,i)=>{const s=stores.filter(x=>x.priority==='alta')[i%3]; let t=mins(i%2?'14:00':'13:00'); push({date:iso(d),start:hm(t),end:hm(t+120),type:'Observe & Coach',title:`Acompañamiento fin de semana · ${s.name}`,store:s.cc,storeName:s.name,manager:s.manager,focus:'Jornada de acompañamiento operativo, hombro a hombro, conexión y mejora continua.',maps:s.maps}); push({date:iso(d),start:hm(t+120),end:hm(t+180),type:'Comida',title:'🍽️ Comida',focus:'Media jornada'}); push({date:iso(d),start:hm(t+180),end:hm(t+300),type:'Conexión rápida',title:`Seguimiento operativo · ${s.name}`,store:s.cc,storeName:s.name,manager:s.manager,focus:'Cierre de compromisos y reconocimiento al equipo.',maps:s.maps});}); }
 // Focus Group julio
 push({date:'2026-07-24',start:'10:00',end:'12:00',type:'Administrativo',title:'Focus Group Subgerentes · Coacalco',store:'38401',storeName:'CC Coacalco',focus:'Escucha de subgerentes: barreras, aprendizajes, operación y propuestas para acelerar resultados.',maps:stores.find(s=>s.cc==='38401').maps});
 // admins recurrentes
 for(let d=new Date(start);d<=end;d=addDays(d,1)){const dow=d.getDay(); if(dow==1) push({date:iso(d),start:'07:45',end:'08:25',type:'Administrativo',title:'KPI Semanal Portafolio',focus:'Validar KPIs antes de 09:30.'}); if(dow==4) push({date:iso(d),start:'16:30',end:'17:30',type:'Administrativo',title:'Capacitación DM',focus:'Ubits, Attensi o desarrollo.'}); if(dow==3) push({date:iso(d),start:'16:30',end:'17:30',type:'Administrativo',title:'Pendientes de mantenimiento',focus:'Seguimiento a pendientes específicos de mantenimiento.'}); if(d.getDate()>=3&&d.getDate()<=6&&dow>=1&&dow<=5) push({date:iso(d),start:'17:30',end:'18:00',type:'Administrativo',title:'Ingreso de Gastos',focus:'Buscar espacio del 3 al 6.'}); if(d.getDate()==30) push({date:iso(d),start:'09:00',end:'09:30',type:'Administrativo',title:'Factura Parco',focus:'Correo Factura Parco.'}); }
 save();}
function save(){localStorage.setItem('plannerEventsV6',JSON.stringify(events))} function load(){events=JSON.parse(localStorage.getItem('plannerEventsV6')||'[]'); if(!events.length) generateBase()}
function init(){months.forEach(m=>$('monthSel').add(new Option(m,m))); $('monthSel').value='Julio'; ['Todas',...types.map(t=>t.id)].forEach(t=>$('typeSel').add(new Option(t,t))); ['Todas',...stores.map(s=>`${s.cc} · ${s.name}`)].forEach(t=>$('storeSel').add(new Option(t,t))); ['monthSel','weekSel','typeSel','storeSel','searchInput','detailSearch'].forEach(id=>$(id).addEventListener('input',render)); $('generateBtn').onclick=()=>{generateBase();render()}; $('resetBtn').onclick=()=>{localStorage.removeItem('plannerEventsV6');generateBase();render()}; $('blockBtn').onclick=addBlock; $('icsMonthBtn').onclick=()=>downloadICS(filteredMonth(),`Planner_DM_${$('monthSel').value}_2026.ics`); $('icsYearBtn').onclick=()=>downloadICS(events,`Planner_DM_2026.ics`); $('copyRouteBtn').onclick=copyRoute; window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hidden')}); $('installBtn').onclick=()=>deferredPrompt?.prompt(); if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js'); load(); render();}
function selectedEvents(){const m=monthIndex(), y=2026, t=$('typeSel').value, st=$('storeSel').value.split(' ')[0], q=$('searchInput').value.toLowerCase(); let ev=events.filter(e=>date(e.date).getMonth()==m&&date(e.date).getFullYear()==y); if($('weekSel').value!='Todas'){const [a,b]=$('weekSel').value.split('|').map(date); ev=ev.filter(e=>date(e.date)>=a&&date(e.date)<=b)} if(t!='Todas') ev=ev.filter(e=>e.type==t); if(st!='Todas') ev=ev.filter(e=>e.store==st); if(q) ev=ev.filter(e=>JSON.stringify(e).toLowerCase().includes(q)); return ev.sort((a,b)=>(a.date+a.start).localeCompare(b.date+b.start));}
function filteredMonth(){return selectedEvents()}
function render(){const m=monthIndex(); const prevWeek=$('weekSel').value||'Todas'; $('weekSel').innerHTML=''; $('weekSel').add(new Option('Todas','Todas')); getWeeksOfMonth(2026,m).forEach(w=>$('weekSel').add(new Option(w.label,`${w.start}|${w.end}`))); if([...$('weekSel').options].some(o=>o.value===prevWeek)) $('weekSel').value=prevWeek; renderKpis(); renderIntention(); renderCalendar(); renderRouteOptions(); renderDetails();}
function renderKpis(){const ev=selectedEvents(), physical=ev.filter(e=>e.store&&!['Traslado','Comida','Administrativo','Adaptación a lo inesperado'].includes(e.type)); const covered=new Set(physical.map(e=>e.store)); const high=physical.filter(e=>stores.find(s=>s.cc==e.store)?.priority==='alta').length; const k=[['VISITAS MES',physical.length,'actividades físicas'],['TIENDAS CUBIERTAS',`${covered.size}/10`,'portafolio'],['PRIORIDAD ALTA',high,'visitas a tiendas críticas'],['VPP/SOA',physical.filter(e=>e.type==='VPP/SOA').length,'periodo'],['INVENTARIO',physical.filter(e=>e.type==='System Check Inventario').length,'periodo'],['ADAPTACIÓN',ev.filter(e=>e.type==='Adaptación a lo inesperado').length,'espacios protegidos']]; $('kpis').innerHTML=k.map(x=>`<div class="panel kpi"><small>${x[0]}</small><b>${x[1]}</b><span>${x[2]}</span></div>`).join('')}
function renderIntention(){const mid=new Date(2026,monthIndex(),15), p=periodFor(mid); $('intention').innerHTML=`<h2>Intencionalidad</h2><div class="intCard"><h3>${p.name}</h3><p><b>Planificación:</b> ${p.planStart} a ${p.planEnd}</p><p><b>Campaña:</b> ${p.campStart} a ${p.campEnd}</p><p><b>Regla:</b> 1 VPP/SOA, 1 Observe & Coach, 1 Inventario y 1 Conexión por tienda en el periodo.</p></div><div class="intCard"><h3>Approach DM</h3><p>Preparar → trabajar hombro a hombro → dar seguimiento. Conversaciones con valentía, pertenencia y enfoque humano.</p><span class="pill alta">Alta: Luna, Cosmo N1, Patio</span><span class="pill media">Media: Apropiación</span><span class="pill estable">Estable: Asesoramiento</span></div>`}
function renderCalendar(){const m=monthIndex(), first=new Date(2026,m,1), start=addDays(first,-((first.getDay()+6)%7)), last=new Date(2026,m+1,0); $('calTitle').textContent=`Agenda · ${months[m]} 2026`; $('legend').innerHTML=types.map(t=>`<span style="--c:${t.color}">${t.label}</span>`).join('')+`<span style="--c:#00a86b">🚀 Arranque campaña</span>`; let html=['L','M','X','J','V','S','D'].map(d=>`<div class="dow">${d}</div>`).join(''); for(let i=0;i<42;i++){const d=addDays(start,i), ds=iso(d), ev=selectedEvents().filter(e=>e.date==ds); html+=`<div class="day ${d.getMonth()!=m?'muted':''}"><div class="num">${d.getDate()}</div>`+ev.slice(0,7).map(e=>`<div class="event ${e.protected?'protected':''}" style="--c:${typeColor(e.type)}" title="${e.title}">${e.start} ${e.title}</div>`).join('')+(ev.length>7?`<div class="more">+${ev.length-7} más</div>`:'')+`</div>`} $('calendar').innerHTML=html;}
function renderRouteOptions(){const ev=selectedEvents().filter(e=>e.store&&!e.routeOnly&&!['Comida','Administrativo'].includes(e.type)); const dates=[...new Set(ev.map(e=>e.date))].sort(); $('routeDateSel').innerHTML=dates.map(d=>`<option value="${d}">${d.slice(8,10)} ${months[Number(d.slice(5,7))-1].slice(0,3)}</option>`).join(''); $('routeDateSel').onchange=renderRoute; renderRoute(); renderCoverage();}
function renderRoute(){const ds=$('routeDateSel').value; const visits=selectedEvents().filter(e=>e.date==ds&&e.store&&!e.routeOnly&&!['Comida','Administrativo'].includes(e.type)); const route=nearestRoute(visits.map(e=>stores.find(s=>s.cc==e.store)).filter(Boolean)); drawRoute(route); let cur=D.home; $('routeList').innerHTML=route.map((s,i)=>{const m=travel(cur,s); const txt=`<div class="routeStep"><b>${i?'Parada '+i:'Salida'}</b><br>${cur.name||'Casa Enrique'} → ${s.name} · ${m} min aprox<br><a href="${s.maps}" target="_blank">Abrir Maps</a></div>`; cur=s; return txt}).join('')+(route.length?`<div class="routeStep"><b>Regreso</b><br>${route.at(-1).name} → Casa Enrique · ${travel(route.at(-1),D.home)} min aprox</div>`:'<p>Sin ruta para el filtro actual.</p>')}
function drawRoute(route){const box=$('routeMap'); box.innerHTML=''; const pts=[...route,D.home]; if(!pts.length)return; const lats=pts.map(p=>p.lat), lngs=pts.map(p=>p.lng); const minLat=Math.min(...lats),maxLat=Math.max(...lats),minLng=Math.min(...lngs),maxLng=Math.max(...lngs); const pos=p=>({x:20+(p.lng-minLng)/(maxLng-minLng||1)*250,y:20+(maxLat-p.lat)/(maxLat-minLat||1)*150}); let prev=D.home; route.concat([D.home]).forEach(p=>{const a=pos(prev),b=pos(p),len=Math.hypot(b.x-a.x,b.y-a.y),ang=Math.atan2(b.y-a.y,b.x-a.x)*180/Math.PI; const e=document.createElement('div'); e.className='edge'; e.style.cssText=`left:${a.x}px;top:${a.y}px;width:${len}px;transform:rotate(${ang}deg)`; box.appendChild(e); prev=p}); pts.forEach(p=>{const o=pos(p); const n=document.createElement('div'); n.className='node '+(p.name==='Casa Enrique'?'home':''); n.style.left=o.x+'px';n.style.top=o.y+'px';n.innerHTML=`<span>${p.short||'Casa'}</span>`; box.appendChild(n)})}
function renderCoverage(){const m=monthIndex(); let html=''; getWeeksOfMonth(2026,m).forEach(w=>{const ev=events.filter(e=>date(e.date)>=date(w.start)&&date(e.date)<=date(w.end)&&e.store&&!['Traslado','Comida'].includes(e.type)); const set=new Set(ev.map(e=>e.store)); html+=`<div class="coverageItem"><b>${w.label}</b><br>${set.size}/10 tiendas · ${set.size===10?'✅ completo':'⚠️ revisar'}</div>`}); $('coverageList').innerHTML=html}
function renderDetails(){let ev=selectedEvents(); const q=$('detailSearch').value?.toLowerCase(); if(q) ev=ev.filter(e=>JSON.stringify(e).toLowerCase().includes(q)); $('detailTable').innerHTML='<tr><th>Fecha</th><th>Hora</th><th>Actividad</th><th>Tienda / Gerente</th><th>Enfoque</th><th>Ruta</th></tr>'+ev.map(e=>`<tr><td>${e.date}</td><td>${e.start}-${e.end}</td><td><b>${e.title}</b><br>${e.type}</td><td>${e.storeName||'-'}<br><small>${e.manager||''}</small></td><td>${e.focus||''}</td><td>${e.maps?`<a href="${e.maps}" target="_blank">Maps</a>`:'-'}</td></tr>`).join('')}
function addBlock(){const a=$('blockFrom').value,b=$('blockTo').value,reason=$('blockReason').value||'Bloqueo'; if(!a||!b)return alert('Selecciona fechas de bloqueo.'); events=events.filter(e=>e.date<a||e.date>b||['Adaptación a lo inesperado'].includes(e.type)); for(let d=date(a);d<=date(b);d=addDays(d,1)) push({date:iso(d),start:'00:00',end:'23:59',type:'Bloqueo',title:`⛔ ${reason}`,focus:'Bloqueo todo el día. Se retiraron visitas físicas del rango.'}); save(); render();}
function downloadICS(ev,name){const fmt=(d,t)=>d.replaceAll('-','')+'T'+t.replace(':','')+'00'; const body=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Planner DM 360//ES'].concat(ev.map(e=>['BEGIN:VEVENT',`UID:${e.id}@planner-dm`, `DTSTAMP:${fmt(iso(new Date()),'00:00')}Z`,`DTSTART:${fmt(e.date,e.start)}`,`DTEND:${fmt(e.date,e.end)}`,`SUMMARY:${e.title}`,`LOCATION:${e.storeName||''}`,`DESCRIPTION:${(e.focus||'').replace(/\n/g,' ')} Ruta: ${e.maps||''}`,'END:VEVENT'].join('\n'))).concat(['END:VCALENDAR']).join('\n'); const blob=new Blob([body],{type:'text/calendar'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=name; a.click();}
function copyRoute(){const text=[...document.querySelectorAll('.routeStep')].map(x=>x.innerText).join('\n'); navigator.clipboard.writeText(text); alert('Ruta copiada')}
init();
