const D=window.PLANNER_DATA, $=id=>document.getElementById(id);
const months=['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];
const types=D.visitTypes, stores=D.stores; let events=[],deferredPrompt=null;
const date=s=>{const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)};
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const addDays=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};
const hm=m=>`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;
const typeInfo=t=>types.find(x=>x.id===t)||{color:'#64748b',minutes:60};
const monthIndex=()=>months.indexOf($('monthSel').value);
function distance(a,b){const R=6371,r=x=>x*Math.PI/180,dl=r(b.lat-a.lat),dn=r(b.lng-a.lng),v=Math.sin(dl/2)**2+Math.cos(r(a.lat))*Math.cos(r(b.lat))*Math.sin(dn/2)**2;return 2*R*Math.asin(Math.sqrt(v));}
function travel(a,b){return Math.max(20,Math.round(distance(a,b)*2.2+20));}
function campaignFor(d){return D.campaigns.find(c=>d>=date(c.planStart)&&d<=date(c.campEnd))||D.campaigns.at(-1)}
function weeksOfMonth(y,m){const first=new Date(y,m,1),last=new Date(y,m+1,0),out=[];let cur=addDays(first,-((first.getDay()+6)%7));while(cur<=last){out.push({label:`${iso(cur).slice(5)} al ${iso(addDays(cur,6)).slice(5)}`,start:iso(cur),end:iso(addDays(cur,6))});cur=addDays(cur,7)}return out}
function push(event){events.push({id:crypto.randomUUID(),...event})}
function addEvent(day,start,type,title,focus,extras={}){const mins=typeInfo(type).minutes;const [h,m]=start.split(':').map(Number);push({date:iso(day),start,end:hm(h*60+m+mins),type,title,focus,campaign:campaignFor(day).id,...extras});}
function priorityFocus(store,index){return ['Experiencia','Conexión','Bebida','Recuperación de órdenes','Duty Roster / limpieza','UKG / cobertura'][index%6];}
function visitMessage(type,store,focus){
 const base={
   'Mejora continua':`Observar ${focus}, escuchar retro y practicar un comportamiento con ${store.manager}. Pregunta: ¿qué hará distinto el líder en la próxima hora?`,
   'Sistema crítico':`Validar el sistema que sostiene ${focus}. Pregunta: ¿dónde se rompe el estándar, quién es dueño y cuál es la evidencia?`,
   'Seguimiento 10 días':`Confirmar avance de la visita anterior. Pregunta: ¿qué cambió, qué no funcionó y qué obstáculo debemos quitar?`,
   'Desarrollo y talento':`Crear capacidad del líder y del equipo. Pregunta: ¿quién necesita práctica, acompañamiento o cobertura para crecer?`,
   'Conversación de desempeño (CDD)':`Conversación de desempeño: preparar, conversar, documentar y acordar siguiente paso.`,
 };
 return `${base[type]||'Alinear prioridades y definir siguiente paso.'} Salida: 1 foco · 1 práctica · 1 dueño · 1 fecha.`;
}
function routineType(day,store,index){if(day.getMonth()===9)return 'Conversación de desempeño (CDD)';if(store.cc==='38604'&&index%2===0)return 'Desarrollo y talento';return ['Mejora continua','Sistema crítico','Seguimiento 10 días','Desarrollo y talento'][index%4]}
function generateBase(){
 events=[];const start=date(D.start),end=date(D.end);
 // Cada tienda se visita una vez cada diez días. La secuencia alterna zonas para que cada jornada tenga una ruta lógica.
 const izcalli=stores.filter(s=>s.zone==='Izcalli'),coacalco=stores.filter(s=>s.zone==='Coacalco–Ecatepec'),ordered=[];
 for(let i=0;i<5;i++){ordered.push(izcalli[i],coacalco[i])}
 ordered.forEach((store,index)=>{for(let d=addDays(start,index);d<=end;d=addDays(d,10)){
   const type=routineType(d,store,index+Math.floor((d-start)/86400000/10)),focus=priorityFocus(store,index),weekend=[0,6].includes(d.getDay());
   addEvent(d,'08:00',type,`${type} · ${store.name}`,visitMessage(type,store,focus),{store:store.cc,storeName:store.name,manager:store.manager,zone:store.zone,isVisit:true,focus});
   if(weekend)addEvent(d,'11:30','Administrativo / soporte','Cierre de fin de semana','Registrar señal de cliente/equipo, reconocer y dejar una acción concreta.',{store:store.cc,storeName:store.name,manager:store.manager,zone:store.zone,focus:'Experiencia en pico'});
   addEvent(d,'15:00','Espacio inesperado','Espacio para lo inesperado','Resolver una barrera, acompañar una recuperación o cerrar un soporte sin desplazar el foco principal.',{zone:store.zone});
 }});
 // Lunes y martes se mantienen administrativos, pero incluyen una visita planificada del ciclo de 10 días.
 for(let d=new Date(start);d<=end;d=addDays(d,1)){
   if(d.getDay()===1){addEvent(d,'11:15','Administrativo / soporte','Lunes · revisar datos y retro','Cruce: Perfil Tienda + CeNtro Partner + WOE + retro de clientes/equipo. Elegir la prioridad de la visita.',{});addEvent(d,'14:00','Administrativo / soporte','Lunes · soporte y revisión','Sistema, Mantenimiento, COA o Capacitación: evidencia, responsable y ETA.',{});}
   if(d.getDay()===2){const firstTue=d.getDate()<=7;addEvent(d,'11:15','Junta Regional',firstTue?'Junta Regional · presencial':'Junta Regional · actualización',firstTue?'Una vez al mes presencial. Llevar datos, retro, riesgo y petición concreta.':'Bajar una prioridad, una conducta y una fecha al equipo.',{isVisit:false});addEvent(d,'13:00','Administrativo / soporte','Martes · bajada al equipo','Traducir la junta en una acción por tienda y actualizar compromisos.',{});}
   if(d.getDay()===5)addEvent(d,'14:00','Desarrollo y talento','Desarrollo DM','Reflexión semanal: ¿cómo habilité a otro a lograr el resultado sin rescatarlo?',{});
 }
 D.campaigns.forEach(c=>{const d=date(c.planStart);addEvent(d,'14:00','PPK · informativo',`PPK · ${c.name}`,c.ppk,{campaign:c.id});});
 save();
}
function save(){localStorage.setItem('plannerEventsV30',JSON.stringify(events))}
function load(){events=JSON.parse(localStorage.getItem('plannerEventsV30')||'[]');if(!events.length)generateBase()}
function selectedEvents(){const m=monthIndex(),type=$('typeSel').value,store=$('storeSel').value.split(' ')[0],campaign=$('campaignSel').value,q=$('searchInput').value.toLowerCase();let out=events.filter(e=>date(e.date).getMonth()===m&&date(e.date).getFullYear()===2026);if($('weekSel').value!=='Todas'){const[a,b]=$('weekSel').value.split('|').map(date);out=out.filter(e=>date(e.date)>=a&&date(e.date)<=b)}if(type!=='Todas')out=out.filter(e=>e.type===type);if(campaign!=='Todas')out=out.filter(e=>e.campaign===campaign);if(store!=='Todas')out=out.filter(e=>e.store===store);if(q)out=out.filter(e=>JSON.stringify(e).toLowerCase().includes(q));return out.sort((a,b)=>(a.date+a.start).localeCompare(b.date+b.start))}
function renderKpis(){const ev=selectedEvents(),visits=ev.filter(e=>e.isVisit),covered=new Set(visits.map(e=>e.store)),critical=visits.filter(e=>e.type==='Sistema crítico').length,cdd=visits.filter(e=>e.type==='Conversación de desempeño (CDD)').length;const k=[['VISITAS MES',visits.length,'1 tienda cada 10 días'],['TIENDAS CUBIERTAS',`${covered.size}/10`,'portafolio'],['SISTEMA CRÍTICO',critical,'limpieza · UKG · inventario'],['CDD',cdd,'desempeño y desarrollo'],['DESARROLLO',visits.filter(e=>e.type==='Desarrollo y talento').length,'Mary + líderes'],['IMPREVISTO',ev.filter(e=>e.type==='Espacio inesperado').length,'espacio protegido']];$('kpis').innerHTML=k.map(x=>`<div class="panel kpi"><small>${x[0]}</small><b>${x[1]}</b><span>${x[2]}</span></div>`).join('')}
function renderIntention(){const c=campaignFor(new Date(2026,monthIndex(),15));$('intention').innerHTML=`<h2>Mi guía DM</h2><div class="intCard"><h3>Antes de entrar</h3><p><b>Dato:</b> Perfil Tienda / CeNtro Partner</p><p><b>Retro:</b> equipo + clientes</p><p><b>Observación:</b> una sola prioridad</p></div><div class="intCard"><h3>En la tienda</h3><p><b>Ver → preguntar → practicar → validar.</b></p><p>No rescates: crea capacidad en el líder.</p><span class="pill alta">Mary · Cosmopol: desarrollo y cobertura</span></div><div class="intCard"><h3>${c.name}</h3><p>${c.ppk}</p><p><b>PPK:</b> información para ejecutar; no es una visita.</p></div>`}
function renderCalendar(){const m=monthIndex(),first=new Date(2026,m,1),start=addDays(first,-((first.getDay()+6)%7));$('calTitle').textContent=`Agenda · ${months[m]} 2026`;$('legend').innerHTML=types.filter(t=>!['Administrativo / soporte','Espacio inesperado'].includes(t.id)).map(t=>`<span style="--c:${t.color}">${t.label}</span>`).join('');let html=['L','M','X','J','V','S','D'].map(d=>`<div class="dow">${d}</div>`).join('');for(let i=0;i<42;i++){const d=addDays(start,i),ev=selectedEvents().filter(e=>e.date===iso(d));html+=`<div class="day ${d.getMonth()!==m?'muted':''}"><div class="num">${d.getDate()}</div>${ev.slice(0,4).map(e=>`<div class="event ${e.type==='Espacio inesperado'?'protected':''}" style="--c:${typeInfo(e.type).color}" title="${e.title}">${e.start} ${e.title}</div>`).join('')}${ev.length>4?`<div class="more">+${ev.length-4} más</div>`:''}</div>`}$('calendar').innerHTML=html}
function renderRouteOptions(){const ev=selectedEvents().filter(e=>e.isVisit),dates=[...new Set(ev.map(e=>e.date))].sort();$('routeDateSel').innerHTML=dates.map(d=>`<option value="${d}">${d.slice(8)} ${months[Number(d.slice(5,7))-1].slice(0,3)}</option>`).join('');$('routeDateSel').onchange=renderRoute;renderRoute();renderCoverage()}
function renderRoute(){const day=$('routeDateSel').value,visits=selectedEvents().filter(e=>e.date===day&&e.isVisit),unique=[...new Map(visits.map(e=>[e.store,e])).values()];if(!unique.length){$('routeMap').innerHTML='';$('routeList').innerHTML='<p>Sin tienda de visita para este filtro.</p>';return}const routeStores=unique.map(e=>stores.find(x=>x.cc===e.store));$('routeMap').innerHTML=`<div class="routeZone"><small>RUTA DEL DÍA</small><b>${routeStores[0].zone}</b><span>${routeStores.map(s=>s.short).join(' → ')}</span><em>Una zona por día. Evita cruzar Izcalli y Coacalco–Ecatepec en la misma jornada.</em></div>`;let cur=D.home;$('routeList').innerHTML=unique.map((e,i)=>{const s=stores.find(x=>x.cc===e.store),mins=travel(cur,s);cur=s;return `<div class="routeStep"><b>${i?'Siguiente tienda':'Llegar 08:00'}</b><br>${s.zone} · ${s.name}<br><small>${i?`${mins} min entre tiendas`:`Casa → tienda: ${mins} min. Considerar salida previa para estar 08:00.`}</small><br><a href="${s.maps}" target="_blank">Abrir Maps</a></div>`}).join('')+`<div class="routeStep"><b>Regreso</b><br>Terminar operación y salir para estar en casa máximo 18:00.</div>`}
function renderCoverage(){const today=new Date(D.start),limit=addDays(today,10);$('coverageList').innerHTML=stores.map(s=>{const next=events.filter(e=>e.store===s.cc&&e.isVisit&&date(e.date)>=today).sort((a,b)=>a.date.localeCompare(b.date))[0];const status=next&&date(next.date)<=limit?'✅ en ciclo':'⚠️ programar';return `<div class="coverageItem"><b>${s.short}</b> · ${s.zone}<br>${next?`${next.date} · ${next.type}`:'Sin visita'} ${status}</div>`}).join('')}
function renderDetails(){let ev=selectedEvents(),q=$('detailSearch').value?.toLowerCase();if(q)ev=ev.filter(e=>JSON.stringify(e).toLowerCase().includes(q));$('detailTable').innerHTML='<tr><th>Fecha</th><th>Hora</th><th>Tipo</th><th>Tienda / líder</th><th>Pregunta y salida</th><th>Campaña</th></tr>'+ev.map(e=>`<tr><td>${e.date}</td><td>${e.start}-${e.end}</td><td><b>${e.title}</b></td><td>${e.storeName||'-'}<br><small>${e.manager||e.zone||''}</small></td><td>${e.focus||''}</td><td>${e.campaign||'-'}</td></tr>`).join('')}
function render(){const m=monthIndex(),prev=$('weekSel').value||'Todas';$('weekSel').innerHTML='';$('weekSel').add(new Option('Todas','Todas'));weeksOfMonth(2026,m).forEach(w=>$('weekSel').add(new Option(w.label,`${w.start}|${w.end}`)));if([...$('weekSel').options].some(o=>o.value===prev))$('weekSel').value=prev;renderKpis();renderIntention();renderCalendar();renderRouteOptions();renderDetails()}
function addBlock(){const a=$('blockFrom').value,b=$('blockTo').value,reason=$('blockReason').value||'Bloqueo';if(!a||!b)return alert('Selecciona fechas de bloqueo.');events=events.filter(e=>e.date<a||e.date>b||!e.isVisit);for(let d=date(a);d<=date(b);d=addDays(d,1))addEvent(d,'08:00','Bloqueo',`⛔ ${reason}`,'Bloqueo; reprogramar visita dentro de los próximos 10 días.',{});save();render()}
function downloadICS(ev,name){const fmt=(d,t)=>d.replaceAll('-','')+'T'+t.replace(':','')+'00',body=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Planner DM 3.0//ES'].concat(ev.map(e=>['BEGIN:VEVENT',`UID:${e.id}@planner-dm`,`DTSTAMP:${fmt(iso(new Date()),'00:00')}Z`,`DTSTART:${fmt(e.date,e.start)}`,`DTEND:${fmt(e.date,e.end)}`,`SUMMARY:${e.title}`,`DESCRIPTION:${(e.focus||'').replace(/\n/g,' ')}`,'END:VEVENT'].join('\n'))).concat(['END:VCALENDAR']).join('\n');const blob=new Blob([body],{type:'text/calendar'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click()}
function init(){months.forEach(m=>$('monthSel').add(new Option(m,m)));$('monthSel').value='Agosto';['Todas',...D.campaigns.map(c=>c.id)].forEach(c=>$('campaignSel').add(new Option(c,c)));['Todas',...types.map(t=>t.id)].forEach(t=>$('typeSel').add(new Option(t,t)));['Todas',...stores.map(s=>`${s.cc} · ${s.name}`)].forEach(s=>$('storeSel').add(new Option(s,s)));['monthSel','weekSel','campaignSel','typeSel','storeSel','searchInput','detailSearch'].forEach(id=>$(id).addEventListener('input',render));$('generateBtn').onclick=()=>{generateBase();render()};$('resetBtn').onclick=()=>{localStorage.removeItem('plannerEventsV30');generateBase();render()};$('blockBtn').onclick=addBlock;$('icsMonthBtn').onclick=()=>downloadICS(selectedEvents(),`Planner_DM_${$('monthSel').value}_2026.ics`);$('icsYearBtn').onclick=()=>downloadICS(events,'Planner_DM_2026.ics');$('copyRouteBtn').onclick=()=>{navigator.clipboard.writeText([...document.querySelectorAll('.routeStep')].map(x=>x.innerText).join('\n'));alert('Ruta copiada')};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hidden')});$('installBtn').onclick=()=>deferredPrompt?.prompt();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');load();render()}
init();
